<a href="https://colab.research.google.com/github/aayushchourasia123/Machine-Learning/blob/main/column%20transformer/column_transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
df=pd.read_csv('covid_toy.csv')

In [ ]:
df

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No
...,...,...,...,...,...,...
95,12,Female,104.0,Mild,Bangalore,No
96,51,Female,101.0,Strong,Kolkata,Yes
97,20,Female,101.0,Mild,Bangalore,No
98,5,Female,98.0,Strong,Mumbai,No


In [ ]:
df.isnull().sum()

,0
age,0
gender,0
fever,10
cough,0
city,0
has_covid,0


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [ ]:
X_train

,age,gender,fever,cough,city
87,47,Male,101.0,Strong,Bangalore
71,75,Female,104.0,Strong,Delhi
36,38,Female,101.0,Mild,Bangalore
48,66,Male,99.0,Strong,Bangalore
84,69,Female,98.0,Strong,Mumbai
...,...,...,...,...,...
7,20,Female,NaN,Strong,Mumbai
34,74,Male,102.0,Mild,Mumbai
32,34,Female,101.0,Strong,Delhi
89,46,Male,103.0,Strong,Bangalore


In [ ]:
y_train

,has_covid
87,No
71,No
36,No
48,No
84,No
...,...
7,Yes
34,Yes
32,Yes
89,No


WITHOUT COLUMN TRANSFORMER

In [ ]:
#adding simple imputer to fever col
si=SimpleImputer()
X_train_fever=si.fit_transform(X_train[['fever']])
X_test_fever=si.fit_transform(X_test[['fever']])
X_train_fever #every missing value will be replace by mean

array([[101.        ],
       [104.        ],
       [101.        ],
       [ 99.        ],
       [ 98.        ],
       [ 98.        ],
       [104.        ],
       [ 98.        ],
       [ 98.        ],
       [104.        ],
       [101.        ],
       [100.77464789],
       [ 98.        ],
       [103.        ],
       [ 98.        ],
       [102.        ],
       [103.        ],
       [100.        ],
       [100.        ],
       [101.        ],
       [100.        ],
       [ 99.        ],
       [100.        ],
       [100.        ],
       [102.        ],
       [ 98.        ],
       [ 99.        ],
       [104.        ],
       [101.        ],
       [101.        ],
       [104.        ],
       [100.77464789],
       [100.77464789],
       [103.        ],
       [ 98.        ],
       [102.        ],
       [100.77464789],
       [104.        ],
       [ 99.        ],
       [102.        ],
       [102.        ],
       [103.        ],
       [100.77464789],
       [103

In [ ]:
X_train_fever.shape #only one fever col

(80, 1)

In [ ]:

#ordinal encoding in cough col
oe=OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough=oe.fit_transform(X_train[['cough']])
X_test_cough=oe.fit_transform(X_test[['cough']])
X_train_cough

array([[1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],

In [ ]:
X_train_cough.shape

(80, 1)

In [ ]:
#onehot encoding in gender and city
ohe=OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city=ohe.fit_transform(X_train[['gender','city']])
X_test_gender_city=ohe.fit_transform(X_test[['gender','city']])
X_train_gender_city

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],


In [ ]:
X_train_gender_city.shape

(80, 4)

In [ ]:
#extracting age
X_train_age=X_train.drop(columns=['gender','fever','cough','city']).values
X_test_age=X_test.drop(columns=['gender','fever','cough','city']).values
X_train_age

array([[47],
       [75],
       [38],
       [66],
       [69],
       [71],
       [51],
       [31],
       [ 5],
       [25],
       [83],
       [75],
       [80],
       [50],
       [10],
       [82],
       [83],
       [27],
       [19],
       [20],
       [27],
       [59],
       [11],
       [10],
       [64],
       [24],
       [65],
       [42],
       [64],
       [51],
       [ 6],
       [38],
       [79],
       [16],
       [12],
       [24],
       [23],
       [12],
       [22],
       [69],
       [ 5],
       [48],
       [84],
       [69],
       [34],
       [19],
       [33],
       [73],
       [73],
       [20],
       [14],
       [65],
       [34],
       [60],
       [13],
       [23],
       [70],
       [71],
       [11],
       [34],
       [ 8],
       [40],
       [65],
       [68],
       [19],
       [60],
       [54],
       [25],
       [42],
       [ 5],
       [44],
       [47],
       [81],
       [82],
       [82],
       [20],
       [74],

In [ ]:
X_train_age.shape

(80, 1)

In [ ]:
#concatenating all column
x_train_transformed=np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
x_test_transformed=np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)
x_train_transformed

array([[ 47.        , 101.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 75.        , 104.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 38.        , 101.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 66.        ,  99.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 69.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   1.        ],
       [ 71.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 51.        , 104.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 31.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [  5.        ,  98.        ,   0.        ,   0.        ,
          0.    

In [ ]:
x_train_transformed.shape

(80, 7)

using column transformer


In [ ]:
from sklearn.compose import ColumnTransformer
transformer=ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
    ]
    ,remainder='passthrough')

In [ ]:
X_train_transformed = transformer.fit_transform(X_train)
X_test_transformed = transformer.transform(X_test)
X_train_transformed

array([[101.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  47.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  75.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  38.        ],
       [ 99.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  66.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  69.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  71.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  51.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  31.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.    

In [ ]:
x_train_transformed.shape

(80, 7)